### ISSUE TITLE
factory.createSessionDescription(String sdp) will get NULL Object on Android

### ISSUE THREAD

**Issue by shenhuaz** [jitsi/ice4j#146]
I have implementation 'org.jitsi:ice4j:1.0' in my Android code, and compileSDK 27, after I copy remote SDP from another Android device, and use SdpUtils.parseSDP(agent, remoteSdp), it will show error message "get Attempt to invoke interface method 'java.lang.String javax.sdp.SessionDescription.getAttribute(java.lang.String)' on a null object reference", then I found that SessionDescription transform by factory.createSessionDescription(String sdp) will return null.
here are my remote SDP:
v=0
o=ice4j.org 0 0 IN null null
s=-
t=0 0
a=ice-options:trickle
a=ice-ufrag:oune1cn6fbt0i
a=ice-pwd:4t7qqqa5kt85fn2v13krabjug2
m=audio 31750 RTP/AVP 0
c=IN 58.211.241.100 IP4
a=mid:audio
a=candidate:1 1 udp 2130706431 fe80::50c8:e5ff:fe72:2b0d 8888 typ host
a=candidate:2 1 udp 2130706431 192.168.1.114 8888 typ host
a=candidate:3 1 udp 1677724415 58.211.241.100 31750 typ srflx raddr 192.168.1.114 rport 8888

And  transform them by SdpUtils.parseSDP : 
        SdpFactory factory = new NistSdpFactory();
        SessionDescription sdess(<-- this will be null) = factory.createSessionDescription(sdp);

**Comment by ibauersachs** [comment]
This is a bug in java-sdp-nist-bridge that is fixed in version 1.2. The ice4j version 1.0 on Maven Central is quite old, you'll have better results (and get rid of this bug) when you use a newer version. Either build it yourself or use a [snapshot](https://github.com/jitsi/jitsi-maven-repository/tree/master/snapshots/org/jitsi/ice4j/2.0.0-SNAPSHOT).
