### ISSUE TITLE
I can't manage to make org.ice4j.ice.harvest.DISABLE_LINK_LOCAL_ADDRESSES work

### ISSUE THREAD

**Issue by pierreozoux** [jitsi/ice4j#220]
I run using your docker setup.
One little thing is that it keeps announcing the public and the private IP of the jvb.

I noticed this PR - https://github.com/jitsi/ice4j/pull/156/files

I tried in the jvb.conf:
```
ice4j {
    harvest {
        use-link-local-addresses = false
        mapping {
            stun {

                addresses = [ "meet-jit-si-turnrelay.jitsi.net:443" ]

            }
        }
    }
}
```

And in the sip communicator part:
```

```

But I never see the log - https://github.com/jitsi/ice4j/pull/156/files#diff-033253f38c6d3ff2c8df4a30945167f382675c7ff1ce202e7eb0324bbf43c019R341
```
                 logger.info("Not using link-local address " + address +" for" 
```

in the jvb logs.

And I see the private IP is still advertised.

I'd like to only see the public IP, I guess it is a bit slowing down the clients.

Beside writing down this issue, I have no more idea where to search. Is jvb using this piece of code? Because reading the code it should do what it is written :) Except if 172.19.0.6/16 is not a local IP address?

Ok, actually, I check, and it looks like:
 - isLinkLocalAddress // Example: 10.0.0.0, 172.16.0.0, 192.168.0.0, fec0::/10 (deprecated)
 - inetAddress.isSiteLocalAddress() // Example: 169.254.0.0/16, fe80::/10

(Found it [here](https://www.programcreek.com/java-api-examples/?class=java.net.InetAddress&method=isLinkLocalAddress)

So my question is: is link local address behaving according to your expectation?

And/Or how can I stop jvb to advertise it's local IP?

Thanks a lot for your help :)

**Comment by bgrozev** [comment]
Hey @pierreozoux,

The link-local address options work as expected, but:
1. They will not always print the warning you expect, since that's only for TCP and there's a separate code path for UDP that doesn't print the warning.
2. They affect [link-local addresses](https://en.wikipedia.org/wiki/Link-local_address) as intended, but the address you care about is proobably not link-local.


Advertising both the local address on the interface as well as the public address is also expected, and there is currently no way to suppress the local address. I agree there's value in this option to reduce the number of candidatees, but I think the best place to implement it is in jitsi-videobridge.

**Comment by pierreozoux** [comment]
Thanks for the feedback :) I'll then search/open an issue on the jvb.
