### ISSUE TITLE
Add support of multiple streams with the same media type.

### ISSUE THREAD

**Issue by Horcrux7** [jitsi/ice4j#266]
If I want create multiple video streams with:

```
IceMediaStream video1 = agent.createMediaStream( "video" );
IceMediaStream video2 = agent.createMediaStream( "video" );
```
Then the second call override the first call. If i use a unique names:
```
IceMediaStream video1 = agent.createMediaStream( "video1" );
IceMediaStream video2 = agent.createMediaStream( "video2" );
```
then the media type is changed which is wrong.

It required a method:

```
IceMediaStream createMediaStream(String streamName, String mediaType)
```

**Comment by bgrozev** [comment]
Media streams in ice4j are not associated with a specific media type, they just have a generic name. What do you mean by "the media type is changed" if you use "video1" and "video2" as names?

**Comment by Horcrux7** [comment]
In the method org.ice4j.ice.sdp.IceSdpUtils.initSessionDescription(SessionDescription, Agent) in [line 283](https://github.com/jitsi/ice4j/blob/76e8a1968dbb7df8a0e0708b308edcbd710adbf8/src/main/java/org/ice4j/ice/sdp/IceSdpUtils.java#L283) it use the name of the stream as media type for creation the MediaDescription.

**Comment by bgrozev** [comment]
I see, that's the old code for generating SDP. 

Why do you need multiple streams anyway? Why multiple video streams? Can't you multiplex everything like webrtc does with rtcpmux+bundle? I'm trying to judge if adding a separate "media type" field is an addition worth having in the project.

**Comment by Horcrux7** [comment]
Thank you for your answer. I can't answer your question yet. I am new to WebRTC. Based on the [samples](https://github.com/jitsi/ice4j/tree/master/src/test/java/test) of the project I have thing that every track in the browser match to a stream. If I understand you correct then I am wrong. Only to use one socket seems a large improvement. I will evaluate it.

**Comment by bgrozev** [comment]
These samples are outdated and not suitable for WebRTC. A PeerConnection in the browser has a single ICE session with a single ICE stream. This would correspond to an Agent with a single IceMediaStream (and a single Component, since rtp and rtcp are muxed).

We don't have modern samples, but you can [see how Agent is used in jitsi-videobridge](https://github.com/jitsi/jitsi-videobridge/blob/master/jvb/src/main/kotlin/org/jitsi/videobridge/transport/ice/IceTransport.kt#L114) to connect to a browser on the other end. We translate the SDP to Jingle early on in javascript, so the backend doesn't see any of it. You'll also need to handle DTLS/SRTP which ice4j itself doesn't do.

**Comment by Horcrux7** [comment]
Thanks for your information. I will restart. We can close this ticket.
